apiVersion: v1
kind: ConfigMap
metadata:
  name: wva-scaling-policy-config
  labels:
    app.kubernetes.io/instance: llm-scaling-manager
    app.kubernetes.io/name: workload-variant-autoscaler
    app.kubernetes.io/managed-by: kustomize
data:
  default: |
    analyzerName: saturation
    scaleUpThreshold: 0.85
    scaleDownBoundary: 0.70
    kvCacheThreshold: 0.80
    queueLengthThreshold: 5
    kvSpareTrigger: 0.1
    queueSpareTrigger: 3
