#!/usr/bin/env bash
# Execute render_default_scaledobject and assert the KEDA fallback stanza it
# emits is the one WVA's abstain path depends on.
#
# This is not style checking. WVA returns a gRPC error from GetMetrics when it
# has no trusted view of a workload, and KEDA's executor decides what that means
# from this stanza alone:
#
#     case isError && Spec.Fallback != nil && Spec.Fallback.Replicas != 0:
#
# Miss that branch and the next one calls scaleToZeroOrIdle, so a ScaledObject
# with minReplicaCount: 0 and fallback.replicas: 0 turns "WVA cannot see this
# workload" into "scale the fleet to zero". The floor is therefore load-bearing
# and cannot be left to a comment.
#
# Called from `make lint-deploy-scripts`, which CI runs. A check behind a target
# nobody runs is a check nobody runs.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
# shellcheck source=/dev/null
source "$REPO_ROOT/deploy/lib/scaledobject.sh"

failures=0

fail() {
    printf '  FAIL %s\n' "$1"
    failures=$((failures + 1))
}

ok() {
    printf '  ok   %s\n' "$1"
}

# field <yaml> <path> -- reads one field without needing yq, so this runs
# wherever bash does. The stanza is generated by us and its shape is fixed, so a
# line match is exact enough and its failure mode is a visible miss, not a wrong
# answer.
field() {
    printf '%s\n' "$1" | sed -n "s/^    $2: //p" | head -1
}

check_fallback() {
    local desc="$1" min="$2" max="$3" want_replicas="$4"
    local rendered
    rendered=$(render_default_scaledobject chat Deployment chat-decode default/default \
        "wva-external-scaler.wva-system.svc.cluster.local:9090" "$min" "$max" 10.0)

    if ! printf '%s\n' "$rendered" | grep -q '^  fallback:'; then
        fail "$desc: no fallback stanza emitted"
        return
    fi

    local replicas threshold behavior
    replicas=$(field "$rendered" replicas)
    threshold=$(field "$rendered" failureThreshold)
    behavior=$(field "$rendered" behavior)

    if [ "$replicas" != "$want_replicas" ]; then
        fail "$desc: fallback.replicas is '$replicas', want '$want_replicas'"
    elif [ "$replicas" = "0" ]; then
        fail "$desc: fallback.replicas is 0, which deactivates the workload"
    else
        ok "$desc: fallback.replicas is $replicas"
    fi

    if [ -n "$threshold" ] && [ "$threshold" != "0" ]; then
        ok "$desc: failureThreshold is $threshold"
    else
        fail "$desc: failureThreshold is '$threshold'"
    fi

    if [ "$behavior" = "currentReplicasIfHigher" ]; then
        ok "$desc: behavior is $behavior"
    else
        fail "$desc: behavior is '$behavior', want currentReplicasIfHigher"
    fi
}

echo "Checking the generated ScaledObject's KEDA fallback stanza..."

check_fallback "min=1"  1 10 1
# The case that matters: a scale-to-zero install must NOT inherit replicas: 0.
check_fallback "min=0 (scale-to-zero)" 0 10 1

# An operator override is honoured, except for 0, which has no state in which it
# does what its name says.
#
# Set and unset in THIS shell rather than in a ( subshell ). A subshell gets its
# own copy of the failure counter, so a regression here printed FAIL and still
# exited 0 -- the check reporting success while showing its own failure. Caught
# by running this script against a build with the floor removed, which is the
# only way that class of bug shows up.
export WVA_SO_FALLBACK_REPLICAS=3
check_fallback "override=3" 1 10 3
export WVA_SO_FALLBACK_REPLICAS=0
check_fallback "override=0 is corrected" 1 10 1
unset WVA_SO_FALLBACK_REPLICAS

# The trigger must leave metricType unset: KEDA defaults an external trigger to
# AverageValue, and the fallback metric is target x replicas, which lands on
# exactly replicas only because the advertised target is 1.
rendered=$(render_default_scaledobject chat Deployment chat-decode default/default addr:9090 1 10)
if printf '%s\n' "$rendered" | grep -q 'metricType:'; then
    fail "trigger sets metricType, which changes the fallback arithmetic"
else
    ok "trigger leaves metricType unset (AverageValue)"
fi

if [ "$failures" -ne 0 ]; then
    printf '\n%d check(s) failed\n' "$failures"
    exit 1
fi

echo "ScaledObject fallback stanza OK"
